export const PARAMETER_KEYS = {
	messageSrv: "SERVER_INFO_MESSAGE",
	homePageUrl: "SERVER_INFO_HOMEPAGE_URL",
	facebookUrl: "SERVER_INFO_FACEBOOK_URL",
	twitterUrl: "SERVER_INFO_TWITTER_URL",
	discordUrl: "SERVER_INFO_DISCORD_URL",
	serverName: "SERVER_INFO_NAME",
	country: "SERVER_INFO_COUNTRY",
	timezone: "SERVER_INFO_TIMEZONE",
	bannerUrl: "SERVER_INFO_BANNER_URL",
	adminList: "SERVER_INFO_ADMINS",
	ownerList: "SERVER_INFO_OWNERS",
	secondsToShutDown: "SERVER_INFO_SHUTDOWN_TIMER",
	allowedCountries: "SERVER_INFO_ALLOWED_COUNTRIES",
	activatedHolidaySceneryGroups: "SERVER_INFO_ENABLED_SCENERY",
	disactivatedHolidaySceneryGroups: "SERVER_INFO_DISABLED_SCENERY",
	happyHourEnabled: "happyHourEnabled",
	happyHourMultipler: "happyHourMultipler",
	webSignupUrl: "SERVER_INFO_SIGNUPURL",
	webRecoveryUrl: "SERVER_INFO_RESETURL",
	webPanelUrl: "SERVER_INFO_WEBPANEL",
	cashRewardMultiplier: "CASH_REWARD_MULTIPLIER",
	repRewardMultiplier: "REP_REWARD_MULTIPLIER",
	discordApplicationID: "SERVER_INFO_DISCORDAPPLICATIONID",
	modernAuthSupport: "MODERN_AUTH_ENABLED",
	requireTicket: "TICKET_TOKEN",
} as const;

export type ParameterKey = (typeof PARAMETER_KEYS)[keyof typeof PARAMETER_KEYS];
